// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace ThemeSample
{
	public partial class ColorChoiceController : UIViewController
	{
		public ColorChoiceController (IntPtr handle) : base (handle)
		{
		}
	}
}
